remote_theme: "mmistakes/minimal-mistakes@4.22.0"
title: Johan Hellmark
subtitle: A portfolio.
# logo: assets/img/businessman-310819_1280.png
description: "Contact me at: <br /> Johan.hellmark50@gmail.com"
author: Johan Hellmark 
url: "https://hellmarkjohan.github.io/"
baseurl: ""
repository: "HellmarkJohan/hellmarkJohan.github.io"
source: .

include:
  - _pages
plugins:
  - jekyll-include-cache
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: splash
      author_profile: true
