remote_theme: "mmistakes/minimal-mistakes@4.22.0"
title: Johan Hellmark
# logo: assets/img/businessman-310819_1280.png
description: "Contact me at: <br /> Johan.hellmark50@gmail.com"
author: Johan Hellmark 
url: "https://hellmarkjohan.github.io/"
repository: "HellmarkJohan/hellmarkJohan.github.io"
source: .
plugins:
  - jekyll-include-cache
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
