theme: jekyll-theme-minimal
title: Johan Hellmark
description: Contact me at: \n Johan.hellmark50@gmail.com
author: Johan Hellmark 
baseurl: ""
source: .
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
