theme: jekyll-theme-minimal
title: Johan Hellmark
description: [A portfolio.]
baseurl: ""
source: .
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
