remote_theme: "mmistakes/minimal-mistakes@4.22.0"
title: Johan Hellmark
subtitle: A portfolio.
# logo: assets/img/businessman-310819_1280.png
description: "Contact me at: <br /> Johan.hellmark50@gmail.com"
url: "https://hellmarkjohan.github.io/"
baseurl: ""
repository: "HellmarkJohan/hellmarkJohan.github.io"
include: 
  - _pages

plugins:
  - jekyll-include-cache
  
author:
  name: "Johan Hellmark "
  avatar: "/assets/images/bio-photo.jpg"
  bio: "A driven  engineer whith diverse set of skills combining software, mathematics and management." # Note: Markdown is allowed
  location: "Lund/Malmö, Sweden"
  links:
    - label: "Made Mistakes"
      icon: "fas fa-fw fa-link"
      url: "https://mademistakes.com"
    - label: "Linkedin"
      icon: "fa-linkedin-square"
      url: "https://www.linkedin.com/in/johan-hellmark-689236206/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mmistakes"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/mmistakes"

